config/routes.rb
Rails.application.routes.draw do
  resources :music_titles
  resources :albumnames
  
  get 'category/:id' => 'overallconfigs#category'
  
  get 'musictitle/:id' => 'overallconfigs#musictitle'

  get 'albumnames/index'

  get 'albumnames/show'

  get 'artistnames/show'

  get 'artistnames/index'

  get 'overallconfigs/index'

  get 'overallconfigs/show'
  root 'overallconfigs#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/album_name.rb
class AlbumName < ApplicationRecord
  has_many :musictitles
  belongs_to :artistname
  belongs_to :overallconfig
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist_name.rb
class ArtistName < ApplicationRecord
  has_many :albumnames
  belongs_to :overallconfig
end

app/models/music_title.rb
class MusicTitle < ApplicationRecord
  mount_uploader :video, VideoUploader 
  validates :title, :video, :presence => true
  belongs_to :overallconfig
  belongs_to :albumname
end

app/models/over_all_config.rb
class OverAllConfig < ApplicationRecord
  has_many :musictitles
  has_many :artistnames
  has_many :albumnames
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/music_titles_controller.rb
class MusicTitlesController < ApplicationController
  #before_action :set_music_title, only: [:show, :edit, :update, :destroy]

  # GET /music_titles
  # GET /music_titles.json
  def index
    #@music_title = MusicTitle.where('albumname_id = ?', params[:id])
  end

  # GET /music_titles/1
  # GET /music_titles/1.json
  def show
     @music_title = MusicTitle.where('albumname_id = ?', params[:id])

  end

  # GET /music_titles/new
  def new
    @music_title = MusicTitle.new
  end

  # GET /music_titles/1/edit
  def edit
  end

  # POST /music_titles
  # POST /music_titles.json
  def create
    @music_title = MusicTitle.new(music_title_params)

    respond_to do |format|
      if @music_title.save
        format.html { redirect_to @music_title, notice: 'Music title was successfully created.' }
        format.json { render :show, status: :created, location: @music_title }
      else
        format.html { render :new }
        format.json { render json: @music_title.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /music_titles/1
  # PATCH/PUT /music_titles/1.json
  def update
    respond_to do |format|
      if @music_title.update(music_title_params) && @musictitle.video.recreate_versions!
        format.html { redirect_to @music_title, notice: 'Music title was successfully updated.' }
        format.json { render :show, status: :ok, location: @music_title }
      else
        format.html { render :edit }
        format.json { render json: @music_title.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /music_titles/1
  # DELETE /music_titles/1.json
  def destroy
    @music_title.destroy
    respond_to do |format|
      format.html { redirect_to music_titles_url, notice: 'Music title was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_music_title
      @music_title = MusicTitle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def music_title_params
      params.require(:music_title).permit(:title, :video)
    end
end

app/controllers/overallconfigs_controller.rb
class OverallconfigsController < ApplicationController
  def index
   @musictitle = MusicTitle.page(params[:page])
   @artistname = ArtistName.all
   @overallconfig = OverAllConfig.all   
  end

  def category
   @albumname = AlbumName.where('artistname_id = ?', params[:id])
  end
  
  def musictitle
    @music_title = MusicTitle.where('albumname_id = ?', params[:id])

  end
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/music_titles_helper.rb
module MusicTitlesHelper
end

app/helpers/overallconfigs_helper.rb
module OverallconfigsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfoliodevelop2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/music_titles/_form.html.erb
<%= form_with(model: music_title, local: true) do |form| %>
  <% if music_title.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(music_title.errors.count, "error") %> prohibited this music_title from being saved:</h2>

      <ul>
      <% music_title.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :music_title_title %>
  </div>

  <div class="field">
    <%= form.label :video %>
    <%= form.text_field :video, id: :music_title_video %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/music_titles/edit.html.erb
<h1>Editing Music Title</h1>

<%= render 'form', music_title: @music_title %>

<%= link_to 'Show', @music_title %> |
<%= link_to 'Back', music_titles_path %>

app/views/music_titles/index.html.erb
<!--<p id="notice"><#%= notice %></p>

<h1>Music Titles</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Video</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <#% @music_titles.each do |music_title| %>
      <tr>
        <td><#%= music_title.title %></td>
        <td><#%= music_title.video %></td>
        <td><#%= link_to 'Show', music_title %></td>
        <td><#%= link_to 'Edit', edit_music_title_path(music_title) %></td>
        <td><#%= link_to 'Destroy', music_title, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <#% end %>
  </tbody>
</table>

<br>

<#%= link_to 'New Music Title', new_music_title_path %>
-->
<% @music_title.each do |m| %>
 <p><%= m.title %>
    <%= m.video %>
 </p>
<hr>
<% end %>

app/views/music_titles/new.html.erb
<h1>New Music Title</h1>

<%= render 'form', music_title: @music_title %>

<%= link_to 'Back', music_titles_path %>

app/views/music_titles/show.html.erb
<!--<p id="notice"><#%= notice %></p>

<p>
  <strong>Title:</strong>
  <#%= @music_title.title %>
</p>

<p>
  <strong>Video:</strong>
  <#%= @music_title.video %>
</p>

<#%= link_to 'Edit', edit_music_title_path(@music_title) %> |
<#%= link_to 'Back', music_titles_path %>-->

<% @music_title.each do |m| %>
 <p> <%= m.title %>
    <%= link_to m.video_url.to_s do %>
      <%= image_tag(m.video_url(:screenshot).to_s, id: "video", :alt => "screenshot") %>
    <% end %>
</p>
<hr>
<% end %>
  

app/views/overallconfigs/category.html.erb
<h1>＿＿のアルバム一覧</h1>
<p>
<% @albumname.each do |a| %>
  <a href="/musictitle/<%= a.id %>"><%= a.name %></a>
<hr>
<% end %>
</p>

app/views/overallconfigs/index.html.erb
<% @overallconfig.each do |o| %>
 <h1><%= o.title %></h1>
<% end %>
<div class="container">
<% @artistname.each do |a| %> 
 <nav><a href="/category/<%= a.id %>"><%= a.name %></a></nav>
<% end %>

<div class="title_container">
<%= page_entries_info @musictitle %>
<% @musictitle.each do |m| %> 
 <p><%= m.title %>
   <%= link_to m.video_url.to_s do %>
   <%= image_tag(m.video_url(:screenshot).to_s, id: "video", :alt => "screenshot") %>
<% end %></p>
<hr> 

<% end %>

<%= paginate @musictitle %>
</div>
</div>

app/views/overallconfigs/musictitle.html.erb
<% @music_title.each do |m| %>
 <p> <%= m.title %>
    <%= link_to m.video_url.to_s do %>
      <%= image_tag(m.video_url(:screenshot).to_s, id: "video", :alt => "screenshot") %>
    <% end %>
</p>
<hr>
<% end %>

app/views/overallconfigs/show.html.erb
<h1>Overallconfigs#show</h1>
<p>Find me in app/views/overallconfigs/show.html.erb</p>